import Image from "next/image";
import Link from "next/link";
import { Product } from "@/types/api";

export function formatTWD(amount: string | number | null | undefined) {
  const num = Number(amount);
  if (isNaN(num)) return "NT$ 0";
  return `NT$ ${num.toLocaleString("zh-TW", { minimumFractionDigits: 0, maximumFractionDigits: 0 })}`;
}

export function formatIDR(amount: string | number | null | undefined) {
  const num = Number(amount);
  if (isNaN(num)) return "Rp 0";
  return `Rp ${num.toLocaleString("id-ID", { minimumFractionDigits: 0, maximumFractionDigits: 0 })}`;
}

interface ProductCardProps {
  product: Product;
}

export function ProductCard({ product }: ProductCardProps) {
  const imageUrl =
    product.images && product.images.length > 0
      ? product.images[0].url
      : "/placeholder.svg";

  // Using the wa_link if generated by backend, or falling back to a direct wa.me link
  const waMessage = encodeURIComponent(
    `Halo Yuni Counter, saya tertarik dan ingin tanya tentang unit: *${product.name}* (Harga: ${formatTWD(product.price)}). Apakah masih tersedia?`
  );
  // Ideally this comes from settings, falling back to default number
  const waUrl = product.wa_link || `https://wa.me/886987872888?text=${waMessage}`;

  return (
    <div className="group rounded-[var(--radius-lg)] overflow-hidden relative bg-[var(--card-bg)] border border-[var(--border)] text-left flex flex-col transition-all duration-300 hover:border-[var(--border-red)] hover:shadow-[0_12px_32px_rgba(227,48,56,0.12)] hover:-translate-y-1 h-full">
      <Link href={`/katalog/${product.slug}`} className="flex-1 flex flex-col">
        {/* Media Thumbnail */}
        <div className="w-full h-[180px] overflow-hidden bg-[var(--card-media-bg)] relative">
          <Image
            src={imageUrl}
            alt={product.name}
            fill
            className="object-cover transition-transform duration-500 group-hover:scale-[1.06]"
            sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw"
          />
          
          {/* Top Left Badges */}
          <div className="absolute top-2.5 left-2.5 flex flex-col gap-1.5 z-10">
            {product.is_featured && (
              <span className="px-2.5 py-1 rounded-md text-[10px] font-bold tracking-[0.5px] uppercase bg-[#111111]/85 text-white backdrop-blur-md">
                Unggulan
              </span>
            )}
            {product.condition === "new" ? (
              <span className="px-2.5 py-1 rounded-md text-[10px] font-bold tracking-[0.5px] uppercase bg-[rgba(227,48,56,0.9)] text-white backdrop-blur-md">
                Baru
              </span>
            ) : (
              <span className="px-2.5 py-1 rounded-md text-[10px] font-bold tracking-[0.5px] uppercase bg-[#F5F5F5]/95 text-[#444] border border-black/10 backdrop-blur-md dark:bg-white/10 dark:text-white dark:border-white/20">
                Bekas
              </span>
            )}
          </div>

          {/* Top Right Badges */}
          <div className="absolute top-2.5 right-2.5 z-10 flex flex-col gap-1.5 items-end">
            <span className="px-2.5 py-1 rounded-md text-[10px] font-bold tracking-[0.5px] uppercase bg-[rgba(227,48,56,0.9)] text-white backdrop-blur-md">
              {product.branch === "room330" ? "Room 330" : product.branch === "room281" ? "Room 281" : "Room 281 & 330"}
            </span>
            {product.stock_status !== "Tersedia" && (
              <span className={`px-2.5 py-1 rounded-md text-[10px] font-bold tracking-[0.5px] uppercase backdrop-blur-md ${
                product.stock_status === "Stok Habis" 
                  ? "bg-[#FEE2E2]/90 text-[#991B1B] border border-[#FCA5A5]" 
                  : "bg-[#FEF3C7]/90 text-[#92400E] border border-[#FCD34D]"
              }`}>
                {product.stock_status}
              </span>
            )}
          </div>
        </div>

        {/* Card Body */}
        <div className="p-5 flex flex-col flex-1">
          <span className="text-[10px] font-bold tracking-[1px] uppercase text-[var(--red)] mb-1.5">
            {product.category?.name || "Kategori"}
          </span>
          <h3 
            className="font-heading text-[15px] md:text-[16px] font-semibold text-[var(--text-heading)] leading-[1.35] mb-2 line-clamp-2 min-h-[43px]"
            title={product.name}
          >
            {product.name}
          </h3>
          
          <p className="text-[12px] text-[var(--body-text)] leading-[1.5] font-light mb-4 line-clamp-2 flex-1">
            {product.description}
          </p>

          <div className="border-t border-[var(--border)] pt-3.5 mt-auto flex items-end justify-between">
            <div>
              <div className="font-heading text-[18px] md:text-[19px] font-bold text-[var(--text-heading)] leading-none">
                {formatTWD(product.price)}
              </div>
              <div className="text-[11px] md:text-[12px] text-[var(--body-text)] mt-1">
                Est. {formatIDR(product.price_idr)}
              </div>
            </div>
          </div>
        </div>
      </Link>

      {/* WhatsApp Action Button */}
      <div className="px-5 pb-5 pt-0 mt-2">
        <a 
          href={waUrl} 
          target="_blank" 
          rel="noreferrer" 
          className="flex items-center justify-center gap-2 w-full py-2.5 bg-[var(--red)] text-white rounded-[var(--radius-sm)] text-[13px] font-semibold border-none cursor-pointer shadow-[0_4px_14px_rgba(227,48,56,0.28)] transition-all duration-200 hover:bg-[var(--red-hover)] hover:shadow-[0_6px_18px_rgba(227,48,56,0.38)] hover:scale-[0.99] z-10 relative"
          onClick={(e) => e.stopPropagation()}
        >
          <svg width="16" height="16" viewBox="0 0 24 24" fill="currentColor"><path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51-.173-.008-.371-.01-.57-.01-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347m-5.421 7.403h-.004a9.87 9.87 0 01-5.031-1.378l-.361-.214-3.741.982.998-3.648-.235-.374a9.86 9.86 0 01-1.51-5.26c.001-5.45 4.436-9.884 9.888-9.884 2.64 0 5.122 1.03 6.988 2.898a9.825 9.825 0 012.893 6.994c-.003 5.45-4.437 9.884-9.885 9.884m8.413-18.297A11.815 11.815 0 0012.05 0C5.495 0 .16 5.335.157 11.892c0 2.096.547 4.142 1.588 5.945L.057 24l6.305-1.654a11.882 11.882 0 005.683 1.448h.005c6.554 0 11.89-5.335 11.893-11.893a11.821 11.821 0 00-3.48-8.413z"/></svg>
          Tanya Unit Ini
        </a>
      </div>
    </div>
  );
}
